import crypto from "node:crypto";import {providers} from "./providers.js";import {exec} from "node:child_process";import {promisify} from "node:util";import fs from "node:fs/promises";import path from "node:path";const shell=promisify(exec);
const SYSTEM=`You are Nexora. Output ONLY JSON. Final: {"type":"final","content":"..."}. Tool: {"type":"tool_call","tool":"terminal|filesystem.read|filesystem.write","arguments":{...},"reason":"..."}. Terminal and writes require approval. Paths are workspace-relative.`;
export class Agent{
 constructor(state,save){this.state=state;this.save=save;this.jobs=new Map()}
 create(message,provider){const t={id:crypto.randomUUID(),message,provider:provider||null,status:"queued",steps:0,trace:[],createdAt:new Date().toISOString()};this.state.tasks.push(t);this.save(this.state);return t}
 queue(id){const t=this.state.tasks.find(x=>x.id===id);if(t&&!this.jobs.has(id))this.jobs.set(id,this.execute(t).finally(()=>this.jobs.delete(id)))}
 async run(message,provider){return this.execute(this.create(message,provider))}
 async execute(t){t.status="running";for(;t.steps<8;t.steps++){const out=await providers.generate(SYSTEM+"\nUSER:"+t.message+"\nTRACE:"+JSON.stringify(t.trace),t.provider);t.provider=out.provider;t.trace.push({kind:"model",text:out.text});let a;try{a=JSON.parse(out.text.replace(/\`\`\`json|\`\`\`/g,"").trim())}catch{t.status="failed";t.error="Invalid action JSON";await this.save(this.state);return t}if(a.type==="final"){t.status="completed";t.result=a.content;await this.save(this.state);return t}if(!["terminal","filesystem.write"].includes(a.tool)){t.trace.push({kind:"tool",tool:a.tool,observation:await this.read(a)});continue}t.pending=a;t.status="awaiting_approval";await this.save(this.state);return t}t.status="failed";t.error="Maximum steps reached";await this.save(this.state);return t}
 async read(a){const root=path.resolve(process.env.NEXORA_WORKSPACE||"workspace"),p=path.resolve(root,a.arguments.path||"");if(p!==root&&!p.startsWith(root+path.sep))throw Error("Path escapes workspace");return await fs.readFile(p,"utf8")}
 async approve(id){const t=this.state.tasks.find(x=>x.id===id);if(!t?.pending)throw Error("No pending approval");const a=t.pending;if(a.tool==="terminal"){const root=path.resolve(process.env.NEXORA_WORKSPACE||"workspace");const r=await shell(a.arguments.command,{cwd:root,timeout:60000});t.trace.push({kind:"tool",tool:"terminal",observation:r})}else{const root=path.resolve(process.env.NEXORA_WORKSPACE||"workspace"),p=path.resolve(root,a.arguments.path||"");if(p!==root&&!p.startsWith(root+path.sep))throw Error("Path escapes workspace");await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,String(a.arguments.content||""));t.trace.push({kind:"tool",tool:"filesystem.write",observation:"written"})}t.pending=null;return this.execute(t)}
 cancel(id){const t=this.state.tasks.find(x=>x.id===id);if(!t)throw Error("Task not found");t.status="cancelled";this.save(this.state);return t}
}
