import crypto from "node:crypto";import {providers} from "./providers.js";import fs from "node:fs/promises";import path from "node:path";import {terminal} from "./tools/terminal.js";
const SYSTEM=`You are Nexora. Output ONLY JSON. Final: {"type":"final","content":"..."}. Tool: {"type":"tool_call","tool":"filesystem.read|filesystem.write|terminal","arguments":{...},"reason":"..."}. terminal and filesystem.write require approval. Paths are workspace-relative. Terminal commands must be native to the detected host environment.`;
export class Agent{
 constructor(state,save){this.state=state;this.save=save;this.jobs=new Map()}
 create(message,provider){const t={id:crypto.randomUUID(),message,provider:provider||null,status:"queued",steps:0,trace:[],createdAt:new Date().toISOString()};this.state.tasks.push(t);this.save(this.state);return t}
 queue(id){const t=this.state.tasks.find(x=>x.id===id);if(t&&!this.jobs.has(id))this.jobs.set(id,this.execute(t).finally(()=>this.jobs.delete(id)))}
 async run(message,provider){return this.execute(this.create(message,provider))}
 async execute(t){t.status="running";await this.save(this.state);for(;t.steps<8;t.steps++){if(t.status==="cancelled")return t;const out=await providers.generate(SYSTEM+"\nUSER:"+t.message+"\nTRACE:"+JSON.stringify(t.trace),t.provider);t.provider=out.provider;t.trace.push({kind:"model",text:out.text});let a;try{a=JSON.parse(out.text.trim().replace(/^\\`\\`\\`json\\s*|\\s*\\`\\`\\`$/g,""))}catch{t.status="failed";t.error="Invalid action JSON";await this.save(this.state);return t}if(a.type==="final"){t.status="completed";t.result=a.content;await this.save(this.state);return t}if(!["filesystem.read","filesystem.write","terminal"].includes(a.tool)){t.status="failed";t.error="Unsupported tool";await this.save(this.state);return t}if(a.tool==="filesystem.read"){const observation=await this.read(a);t.trace.push({kind:"tool",tool:a.tool,observation});continue}t.pending=a;t.status="awaiting_approval";await this.save(this.state);return t}t.status="failed";t.error="Maximum steps reached";await this.save(this.state);return t}
 root(){return path.resolve(process.env.NEXORA_WORKSPACE||"workspace")}
 safePath(p){const root=this.root(),full=path.resolve(root,p||"");if(full!==root&&!full.startsWith(root+path.sep))throw Error("Path escapes workspace");return full}
 async read(a){return fs.readFile(this.safePath(a.arguments.path),"utf8")}
 async approve(id){const t=this.state.tasks.find(x=>x.id===id);if(!t?.pending)throw Error("No pending approval");const a=t.pending;t.pending=null;let observation;if(a.tool==="filesystem.write"){const p=this.safePath(a.arguments.path);await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,String(a.arguments.content??""));observation="written"}else if(a.tool==="terminal"){observation=await terminal(a.arguments.command,this.root(),Math.min(Number(a.arguments.timeout||60000),120000))}else throw Error("Unsupported approval");t.trace.push({kind:"tool",tool:a.tool,observation});return this.execute(t)}
 cancel(id){const t=this.state.tasks.find(x=>x.id===id);if(!t)throw Error("Task not found");t.status="cancelled";this.save(this.state);return t}
}