import crypto from "node:crypto";import path from "node:path";import{providers}from"./providers.js";import{createToolRegistry}from"./tools/registry.js";import{emit}from"./events.js";
const SYSTEM=`You are Nexora, a cross-platform computer operator. Output ONLY JSON. Final: {"type":"final","content":"..."}. Tool: {"type":"tool_call","tool":"terminal|filesystem|git|system|http|process","arguments":{...},"reason":"..."}. Use workspace-relative paths. Never claim an action succeeded without its tool result.`;
export class Agent{
 constructor(state,save,config={}){this.state=state;this.save=save;this.config=config;this.queueRef=null;this.registry=createToolRegistry(this.root(),config.security||{})}
 setQueue(q){this.queueRef=q}
 create(message,provider){const t={id:crypto.randomUUID(),message:String(message),provider:provider||null,status:"queued",steps:0,trace:[],attempt:0,priority:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.state.tasks.push(t);this.save(this.state);emit("task.created",{id:t.id});return t}
 async execute(t){t.status="running";t.updatedAt=new Date().toISOString();await this.save(this.state);emit("task.status",{id:t.id,status:t.status});for(;t.steps<Number(this.config.maxAgentSteps||this.config.agent?.maxSteps||20);t.steps++){if(t.status==="cancelled")return t;const out=await providers.generate(SYSTEM+"\nUSER:"+t.message+"\nTRACE:"+JSON.stringify(t.trace),t.provider);t.provider=out.provider;t.trace.push({kind:"model",text:out.text,at:new Date().toISOString()});let a;try{a=JSON.parse(out.text.trim().replace(/^\\`\\`\\`json\\s*|\\s*\\`\\`\\`$/g,""))}catch{throw Error("Invalid action JSON from provider")}if(a.type==="final"){t.status="completed";t.result=a.content;await this.save(this.state);emit("task.completed",{id:t.id,result:t.result});return t}if(a.type!=="tool_call"||!this.registry.has(a.tool))throw Error("Unsupported tool: "+a.tool);const auth=this.registry.authorize(a.tool,a.arguments||{});if(auth.decision==="deny")throw Error("Blocked by security policy");if(auth.decision==="ask"){t.pending=a;t.pendingRisk=auth.risk;t.status="awaiting_approval";await this.save(this.state);emit("approval.required",{id:t.id,tool:a.tool,arguments:a.arguments,risk:auth.risk});return t}const observation=await this.registry.execute(a.tool,a.arguments||{},this.root());t.trace.push({kind:"tool",tool:a.tool,observation,at:new Date().toISOString()});await this.save(this.state)}throw Error("Maximum agent steps reached")}
 root(){return path.resolve(this.config.workspace||process.env.NEXORA_WORKSPACE||"workspace")}
 async approve(id){const t=this.state.tasks.find(x=>x.id===id);if(!t?.pending)throw Error("No pending approval");t.pending=null;t.pendingRisk=null;t.status="queued";await this.save(this.state);emit("approval.granted",{id:t.id});return this.queueRef?this.queueRef.enqueue(t.id):this.execute(t)}
 cancel(id){const t=this.state.tasks.find(x=>x.id===id);if(!t)throw Error("Task not found");t.status="cancelled";t.cancelledAt=new Date().toISOString();this.save(this.state);emit("task.cancelled",{id});return t}
 retry(id){const t=this.state.tasks.find(x=>x.id===id);if(!t)throw Error("Task not found");t.status="queued";t.error=null;t.attempt=0;t.pending=null;return this.queueRef?this.queueRef.enqueue(id):t}
}